---
- name: check if agent is already installed
  stat:
    path: " {{ aws_cloudwatch_agent_dest }} "
  register: installed

- block:
    - name: Remove existed cloudwatch-agent
      apt:
        name: " {{ aws_cloudwatch_agent_service_name }} "
        state: absent

  when: (installed.stat.exists)
  become: yes
  become_method: sudo

- block:
    - name: add {{ aws_cwa_package }} key
      apt_key:
        state: present
        url: "{{ aws_cwa_package_gpg }}"

    - name: Download the {{ aws_cwa_package }}.deb file
      get_url:
        url: "{{ aws_cwa_package_url }}"
        dest: "/tmp/{{ aws_cwa_package }}.deb"
      changed_when: false

    - name: Download the {{ aws_cwa_package }}.deb.sig file
      get_url:
        url: "{{ aws_cwa_package_signature }}"
        dest: "/tmp/{{ aws_cwa_package }}.deb.sig"
      changed_when: false

    - name: Verify {{ aws_cwa_package }} package signature
      command: gpg --verify {{ aws_cwa_package }}.deb.sig
      register: verified_sig
      failed_when: "'BAD' in verified_sig.stderr"
      changed_when: false
      args:
        executable: /bin/bash
        chdir: /{{ aws_cwa_temp_path }}

    - name: install {{ aws_cwa_package }}.deb
      apt:
        deb: "/{{ aws_cwa_temp_path }}/{{ aws_cwa_package }}.deb"
        state: present

    - name: Symlink amazon-cloudwatch-agent command
      file:
        src: "{{ aws_cloudwatch_agent_dest }}/bin/amazon-cloudwatch-agent"
        dest: "/usr/bin/{{ aws_cloudwatch_agent_service_name }}"
        state: link

    - name: ensure cloudwatch-agent service running and enabled on boot
      service:
        name: "{{ aws_cloudwatch_agent_service_name }}"
        enabled: yes
      notify: 
        - restart cloudwatch-agent

  become: yes
  become_method: sudo
  tags:
    - aws-cloudwatch-agent
    